this is exceptions in Python
